
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NetworkDevelopement
 */
public class AddQuizView extends javax.swing.JFrame {

    /**
     * Creates new form AddQuizView
     */
    public AddQuizView() {
        initComponents();
        this.btngChoice.add(rbtnA);
        this.btngChoice.add(rbtnB);
        this.btngChoice.add(rbtnC);
        this.btngChoice.add(rbtnD);
        rbtnA.setActionCommand("A");
        rbtnB.setActionCommand("B");
        rbtnC.setActionCommand("C");
        rbtnD.setActionCommand("D");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public ButtonGroup getBtngChoice() {
        return btngChoice;
    }
    
    public JTextField getTfChoiceA() {
        return tfChoiceA;
    }
    public JTextField getTfChoiceB() {
        return tfChoiceB;
    }
    public JTextField getTfChoiceC() {
        return tfChoiceC;
    }
    public JTextField getTfChoiceD() {
        return tfChoiceD;
    }
    public JButton getBtnSave1() {
        return btnSave1;
    }

    public JButton getBtnSave2() {
        return btnSave2;
    }

    public JButton getBtnSave3() {
        return btnSave3;
    }

    public JTextField getTfQuestion1() {
        return tfQuestion1;
    }

    public JCheckBox getCbMCA() {
        return cbMCA;
    }

    public JCheckBox getCbMCB() {
        return cbMCB;
    }

    public JCheckBox getCbMCC() {
        return cbMCC;
    }

    public JCheckBox getCbMCD() {
        return cbMCD;
    }

    public JTextField getMultiChoiceA() {
        return multiChoiceA;
    }

    public JTextField getMultiChoiceB() {
        return multiChoiceB;
    }

    public JTextField getMultiChoiceC() {
        return multiChoiceC;
    }
    public JTextField getMultiChoiceD() {
        return multiChoiceD;
    }
    public JTextField getTfAnswer() {
        return tfAnswer;
    }

    public JTextField getTfQuestion3() {
        return tfQuestion3;
    }
    
    public JTextField getTfQuestion2() {
        return tfQuestion2;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btngChoice = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfQuestion1 = new javax.swing.JTextField();
        rbtnA = new javax.swing.JRadioButton();
        rbtnB = new javax.swing.JRadioButton();
        rbtnC = new javax.swing.JRadioButton();
        rbtnD = new javax.swing.JRadioButton();
        btnSave1 = new javax.swing.JButton();
        tfChoiceA = new javax.swing.JTextField();
        tfChoiceB = new javax.swing.JTextField();
        tfChoiceC = new javax.swing.JTextField();
        tfChoiceD = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfQuestion2 = new javax.swing.JTextField();
        btnSave2 = new javax.swing.JButton();
        multiChoiceA = new javax.swing.JTextField();
        multiChoiceB = new javax.swing.JTextField();
        multiChoiceC = new javax.swing.JTextField();
        multiChoiceD = new javax.swing.JTextField();
        cbMCA = new javax.swing.JCheckBox();
        cbMCB = new javax.swing.JCheckBox();
        cbMCC = new javax.swing.JCheckBox();
        cbMCD = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfQuestion3 = new javax.swing.JTextField();
        tfAnswer = new javax.swing.JTextField();
        btnSave3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Add Quize in course ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel1, gridBagConstraints);

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Question");
        jPanel2.add(jLabel2, new java.awt.GridBagConstraints());

        tfQuestion1.setText("jTextField1");
        jPanel2.add(tfQuestion1, new java.awt.GridBagConstraints());

        rbtnA.setText("(A)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(rbtnA, gridBagConstraints);

        rbtnB.setText("(B)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(rbtnB, gridBagConstraints);

        rbtnC.setText("(C)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(rbtnC, gridBagConstraints);

        rbtnD.setText("(D)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(rbtnD, gridBagConstraints);

        btnSave1.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel2.add(btnSave1, gridBagConstraints);

        tfChoiceA.setPreferredSize(new java.awt.Dimension(30, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 49;
        jPanel2.add(tfChoiceA, gridBagConstraints);

        tfChoiceB.setPreferredSize(new java.awt.Dimension(30, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 49;
        jPanel2.add(tfChoiceB, gridBagConstraints);

        tfChoiceC.setPreferredSize(new java.awt.Dimension(30, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 49;
        jPanel2.add(tfChoiceC, gridBagConstraints);

        tfChoiceD.setPreferredSize(new java.awt.Dimension(30, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 49;
        jPanel2.add(tfChoiceD, gridBagConstraints);

        jTabbedPane1.addTab("Choice", jPanel2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Question");
        jPanel3.add(jLabel3, new java.awt.GridBagConstraints());

        tfQuestion2.setText("jTextField2");
        jPanel3.add(tfQuestion2, new java.awt.GridBagConstraints());

        btnSave2.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel3.add(btnSave2, gridBagConstraints);

        multiChoiceA.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 49;
        jPanel3.add(multiChoiceA, gridBagConstraints);

        multiChoiceB.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 49;
        jPanel3.add(multiChoiceB, gridBagConstraints);

        multiChoiceC.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 49;
        jPanel3.add(multiChoiceC, gridBagConstraints);

        multiChoiceD.setText("jTextField4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 49;
        jPanel3.add(multiChoiceD, gridBagConstraints);

        cbMCA.setText("(A)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(cbMCA, gridBagConstraints);

        cbMCB.setText("(B)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel3.add(cbMCB, gridBagConstraints);

        cbMCC.setText("(C)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel3.add(cbMCC, gridBagConstraints);

        cbMCD.setText("(D)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel3.add(cbMCD, gridBagConstraints);

        jTabbedPane1.addTab("Multi Choice", jPanel3);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Question");
        jPanel4.add(jLabel4, new java.awt.GridBagConstraints());

        tfQuestion3.setText("jTextField3");
        jPanel4.add(tfQuestion3, new java.awt.GridBagConstraints());

        tfAnswer.setText("jTextField4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel4.add(tfAnswer, gridBagConstraints);

        btnSave3.setText("Save");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        jPanel4.add(btnSave3, gridBagConstraints);

        jLabel5.setText("Answer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel4.add(jLabel5, gridBagConstraints);

        jTabbedPane1.addTab("Fill Answer", jPanel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 84;
        jPanel1.add(jTabbedPane1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuizView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSave2;
    private javax.swing.JButton btnSave3;
    private javax.swing.ButtonGroup btngChoice;
    private javax.swing.JCheckBox cbMCA;
    private javax.swing.JCheckBox cbMCB;
    private javax.swing.JCheckBox cbMCC;
    private javax.swing.JCheckBox cbMCD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField multiChoiceA;
    private javax.swing.JTextField multiChoiceB;
    private javax.swing.JTextField multiChoiceC;
    private javax.swing.JTextField multiChoiceD;
    private javax.swing.JRadioButton rbtnA;
    private javax.swing.JRadioButton rbtnB;
    private javax.swing.JRadioButton rbtnC;
    private javax.swing.JRadioButton rbtnD;
    private javax.swing.JTextField tfAnswer;
    private javax.swing.JTextField tfChoiceA;
    private javax.swing.JTextField tfChoiceB;
    private javax.swing.JTextField tfChoiceC;
    private javax.swing.JTextField tfChoiceD;
    private javax.swing.JTextField tfQuestion1;
    private javax.swing.JTextField tfQuestion2;
    private javax.swing.JTextField tfQuestion3;
    // End of variables declaration//GEN-END:variables
}
