
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
public class EditChoiceView extends javax.swing.JPanel {
    public EditChoiceView() {
        initComponents();
        this.buttonGroup1.add(rbtnA);
        this.buttonGroup1.add(rbtnB);
        this.buttonGroup1.add(rbtnC);
        this.buttonGroup1.add(rbtnD);
    }
    public EditChoiceView(String question, String a, String b, String c, String d, String answer){
        initComponents();
        this.buttonGroup1.add(rbtnA);
        this.buttonGroup1.add(rbtnB);
        this.buttonGroup1.add(rbtnC);
        this.buttonGroup1.add(rbtnD);
        this.tfQuestion.setText(question);
        this.tfChoiceA.setText(a);
        this.tfChoiceB.setText(b);
        this.tfChoiceC.setText(c);
        this.tfChoiceD.setText(d);
        
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }
    
    public JButton getBtnDelQuiz() {
        return btnDelQuiz;
    }

    public JButton getBtnEditQuiz() {
        return btnEditQuiz;
    }

    public JRadioButton getRbtnA() {
        return rbtnA;
    }

    public JRadioButton getRbtnB() {
        return rbtnB;
    }

    public JRadioButton getRbtnC() {
        return rbtnC;
    }

    public JRadioButton getRbtnD() {
        return rbtnD;
    }

    public JTextField getTfQuestion() {
        return tfQuestion;
    }

    public JTextField getTfChoiceA() {
        return tfChoiceA;
    }

    public JTextField getTfChoiceB() {
        return tfChoiceB;
    }

    public JTextField getTfChoiceC() {
        return tfChoiceC;
    }

    public JTextField getTfChoiceD() {
        return tfChoiceD;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        tfQuestion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbtnA = new javax.swing.JRadioButton();
        tfChoiceA = new javax.swing.JTextField();
        rbtnC = new javax.swing.JRadioButton();
        tfChoiceC = new javax.swing.JTextField();
        rbtnB = new javax.swing.JRadioButton();
        tfChoiceB = new javax.swing.JTextField();
        rbtnD = new javax.swing.JRadioButton();
        tfChoiceD = new javax.swing.JTextField();
        btnDelQuiz = new javax.swing.JButton();
        btnEditQuiz = new javax.swing.JButton();

        tfQuestion.setText("jTextField1");
        tfQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuestionActionPerformed(evt);
            }
        });
        add(tfQuestion);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(rbtnA, gridBagConstraints);

        tfChoiceA.setText("jTextField6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(tfChoiceA, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(rbtnC, gridBagConstraints);

        tfChoiceC.setText("jTextField7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(tfChoiceC, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(rbtnB, gridBagConstraints);

        tfChoiceB.setText("jTextField8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(tfChoiceB, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(rbtnD, gridBagConstraints);

        tfChoiceD.setText("jTextField9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(tfChoiceD, gridBagConstraints);

        add(jPanel2);

        btnDelQuiz.setText("Delete");
        add(btnDelQuiz);

        btnEditQuiz.setText("Edit");
        add(btnEditQuiz);
    }// </editor-fold>//GEN-END:initComponents

    private void tfQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuestionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelQuiz;
    private javax.swing.JButton btnEditQuiz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbtnA;
    private javax.swing.JRadioButton rbtnB;
    private javax.swing.JRadioButton rbtnC;
    private javax.swing.JRadioButton rbtnD;
    private javax.swing.JTextField tfChoiceA;
    private javax.swing.JTextField tfChoiceB;
    private javax.swing.JTextField tfChoiceC;
    private javax.swing.JTextField tfChoiceD;
    private javax.swing.JTextField tfQuestion;
    // End of variables declaration//GEN-END:variables
}
