
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NetworkDevelopement
 */
public class EditChoiceView extends javax.swing.JPanel {

    /**
     * Creates new form EditMultiChoiceView
     */
    public EditChoiceView() {
        initComponents();
        this.buttonGroup1.add(rbtnA);
        this.buttonGroup1.add(rbtnB);
        this.buttonGroup1.add(rbtnC);
        this.buttonGroup1.add(rbtnD);
    }
    public EditChoiceView(String question, String a, String b, String c, String d, String answer){
        this.tfQuestion.setText(question);
        this.rbtnA.setText(a);
        this.rbtnB.setText(b);
        this.rbtnC.setText(c);
        this.rbtnD.setText(d);
        
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }
    
    public JButton getBtnDelQuiz() {
        return btnDelQuiz;
    }

    public JButton getBtnEditQuiz() {
        return btnEditQuiz;
    }

    public JRadioButton getRbtnA() {
        return rbtnA;
    }

    public JRadioButton getRbtnB() {
        return rbtnB;
    }

    public JRadioButton getRbtnC() {
        return rbtnC;
    }

    public JRadioButton getRbtnD() {
        return rbtnD;
    }

    public JTextField getTfQuestion() {
        return tfQuestion;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        tfQuestion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbtnA = new javax.swing.JRadioButton();
        jTextField6 = new javax.swing.JTextField();
        rbtnC = new javax.swing.JRadioButton();
        jTextField7 = new javax.swing.JTextField();
        rbtnB = new javax.swing.JRadioButton();
        jTextField8 = new javax.swing.JTextField();
        rbtnD = new javax.swing.JRadioButton();
        jTextField9 = new javax.swing.JTextField();
        btnDelQuiz = new javax.swing.JButton();
        btnEditQuiz = new javax.swing.JButton();

        tfQuestion.setText("jTextField1");
        tfQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuestionActionPerformed(evt);
            }
        });
        add(tfQuestion);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(rbtnA, gridBagConstraints);

        jTextField6.setText("jTextField6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(jTextField6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(rbtnC, gridBagConstraints);

        jTextField7.setText("jTextField7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(jTextField7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(rbtnB, gridBagConstraints);

        jTextField8.setText("jTextField8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(jTextField8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(rbtnD, gridBagConstraints);

        jTextField9.setText("jTextField9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        jPanel2.add(jTextField9, gridBagConstraints);

        add(jPanel2);

        btnDelQuiz.setText("Delete");
        add(btnDelQuiz);

        btnEditQuiz.setText("Edit");
        add(btnEditQuiz);
    }// </editor-fold>//GEN-END:initComponents

    private void tfQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuestionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelQuiz;
    private javax.swing.JButton btnEditQuiz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JRadioButton rbtnA;
    private javax.swing.JRadioButton rbtnB;
    private javax.swing.JRadioButton rbtnC;
    private javax.swing.JRadioButton rbtnD;
    private javax.swing.JTextField tfQuestion;
    // End of variables declaration//GEN-END:variables
}
