/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NetworkDevelopement
 */
public class EditFieldAnswerView extends javax.swing.JPanel {

    /**
     * Creates new form EditFieldAnswerView
     */
    public EditFieldAnswerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfQuestion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tfAnswer = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnEditQuiz = new javax.swing.JButton();

        tfQuestion.setText("jTextField10");
        tfQuestion.setPreferredSize(new java.awt.Dimension(140, 19));
        add(tfQuestion);

        tfAnswer.setText("jTextField1");
        tfAnswer.setPreferredSize(new java.awt.Dimension(280, 19));
        jPanel3.add(tfAnswer);

        jPanel4.add(jPanel3);

        add(jPanel4);

        jButton2.setText("Delete");
        add(jButton2);

        btnEditQuiz.setText("Edit");
        add(btnEditQuiz);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditQuiz;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField tfAnswer;
    private javax.swing.JTextField tfQuestion;
    // End of variables declaration//GEN-END:variables
}
