/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class AddquizView extends javax.swing.JFrame {

    /**
     * Creates new form AddquizView
     */
    public AddquizView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 102, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 255, 153));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 102));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 204, 204));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jRadioButton2.setText("(D)");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jRadioButton3.setText("(A)");
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jRadioButton4.setText("(B)");
        jRadioButton4.setOpaque(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jRadioButton5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jRadioButton5.setText("(C)");
        jRadioButton5.setOpaque(false);
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jButton1.setText("SAVE");
        kGradientPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 275, 80, 40));

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel2.setText("ข้อที่");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 40, 30));

        jTextField1.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 450, 30));

        jTextField2.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 490, 30));

        jTextField3.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 450, 30));

        jTextField4.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 450, 30));

        jTextField5.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 450, 30));

        jTabbedPane1.addTab("Choice", kGradientPanel2);

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 255, 102));
        kGradientPanel3.setkStartColor(new java.awt.Color(255, 204, 204));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 490, 30));

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel3.setText("ข้อที่");
        kGradientPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 40, 30));

        jTextField7.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 450, 30));

        jTextField8.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 450, 30));

        jTextField9.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 450, 30));

        jTextField10.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 450, 30));

        jButton2.setText("SAVE");
        kGradientPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 275, 80, 40));

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jCheckBox1.setText("(D)");
        jCheckBox1.setOpaque(false);
        kGradientPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jCheckBox2.setText("(A)");
        jCheckBox2.setOpaque(false);
        kGradientPanel3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jCheckBox3.setText("(B)");
        jCheckBox3.setOpaque(false);
        kGradientPanel3.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jCheckBox4.setText("(C)");
        jCheckBox4.setOpaque(false);
        kGradientPanel3.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jTabbedPane1.addTab("Multi Choice", kGradientPanel3);

        kGradientPanel4.setkEndColor(new java.awt.Color(255, 255, 102));
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 204, 204));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("Answer");
        kGradientPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 70, 30));

        jTextField11.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel4.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 490, 30));

        jTextField12.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        kGradientPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 450, 30));

        jLabel5.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel5.setText("ข้อที่");
        kGradientPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 40, 30));

        jButton3.setText("SAVE");
        kGradientPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 275, 80, 40));

        jTabbedPane1.addTab("Fill Answer", kGradientPanel4);

        kGradientPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 710, 360));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        jLabel1.setText("Add Quiz");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddquizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddquizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddquizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddquizView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddquizView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    // End of variables declaration//GEN-END:variables
}
